"use client";
import { AnimatePresence, motion } from "motion/react";
import { ArrowLeft, ArrowRight, Check, Cpu, GitBranch, Sparkles } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { springs } from "@/lib/motion";

const interests=["Software","Hardware","Design","Research","Open Source","Hackathons","AI","Robotics","Cybersecurity","Accessibility"];
const goals=["Make my first contribution","Build a portfolio","Find collaborators","Attend hackathons","Learn by contributing","Work on hardware","Meet developers","Find research opportunities"];
const technologies=["React","TypeScript","JavaScript","Python","Rust","Go","Node.js","Next.js","Arduino","ESP32","KiCad","Figma","PyTorch","TensorFlow","PostgreSQL"];
export function OnboardingClient(){const router=useRouter();const[step,setStep]=useState(0);const[selectedInterests,setInterests]=useState<string[]>([]);const[selectedGoals,setGoals]=useState<string[]>([]);const[skills,setSkills]=useState<string[]>([]);const[level,setLevel]=useState<"STARTING"|"BEGINNER"|"INTERMEDIATE"|"ADVANCED">("BEGINNER");const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");
 const toggle=(arr:string[],set:(v:string[])=>void,x:string)=>set(arr.includes(x)?arr.filter(a=>a!==x):[...arr,x]);
 const finish=async()=>{setBusy(true);setMsg("");const payload={experienceLevel:level,interests:selectedInterests,goals:selectedGoals,openToCollaboration:true,skills:skills.map(name=>({name,level}))};try{const r=await fetch("/api/profile",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(r.status===401){localStorage.setItem("KOBI-pending-profile",JSON.stringify(payload));router.push("/login?apply=1&mode=signup");return}if(!r.ok)throw new Error((await r.json()).error??"Could not save profile");router.push("/")}catch(e){setMsg(e instanceof Error?e.message:"Could not save profile")}finally{setBusy(false)}};
 const screens=[<ChoiceScreen key="i" title="What pulls you in?" description="Choose a few areas. This tunes discovery without locking you into a lane." options={interests} selected={selectedInterests} onToggle={x=>toggle(selectedInterests,setInterests,x)}/>,<div key="s"><h2 className="text-3xl font-semibold tracking-[-.05em]">What can you already work with?</h2><p className="mt-2 text-sm leading-6 text-[#6e786f]">Self-reported skills are shown separately from skills later verified through real contribution evidence.</p><div className="mt-6 grid grid-cols-2 gap-2 sm:grid-cols-3">{technologies.map(x=><Pick key={x} active={skills.includes(x)} onClick={()=>toggle(skills,setSkills,x)}>{x}</Pick>)}</div><div className="mt-7"><div className="text-xs font-semibold uppercase tracking-[.12em] text-[#778178]">Experience level</div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{(["STARTING","BEGINNER","INTERMEDIATE","ADVANCED"] as const).map(x=><Pick key={x} active={level===x} onClick={()=>setLevel(x)}>{x[0]+x.slice(1).toLowerCase()}</Pick>)}</div></div></div>,<ChoiceScreen key="g" title="What are you trying to change?" description="Goals help KOBI Agent choose the right kind of opportunity—not just the most popular repository." options={goals} selected={selectedGoals} onToggle={x=>toggle(selectedGoals,setGoals,x)}/>];
 return <div className="mx-auto max-w-3xl py-8 sm:py-14"><div className="mb-8 flex items-center gap-2">{screens.map((_,i)=><div key={i} className={`h-1 flex-1 rounded-full ${i<=step?"bg-[#245b40]":"bg-black/8"}`}/>)}</div><div className="surface min-h-[500px] rounded-[30px] p-6 sm:p-10"><AnimatePresence mode="wait"><motion.div key={step} initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-16}} transition={springs.snappy}>{screens[step]}</motion.div></AnimatePresence>{msg&&<div className="mt-5 rounded-xl bg-[#fff1ef] px-3 py-2 text-xs text-[#9b342a]">{msg}</div>}<div className="mt-9 flex items-center justify-between border-t border-black/7 pt-5"><button onClick={()=>step?setStep(step-1):router.back()} className="inline-flex h-10 items-center gap-2 rounded-xl px-3 text-sm font-medium text-[#677168]"><ArrowLeft className="size-4"/>Back</button>{step<screens.length-1?<button onClick={()=>setStep(step+1)} className="inline-flex h-10 items-center gap-2 rounded-[13px] bg-[#163c2d] px-4 text-sm font-semibold text-white">Continue <ArrowRight className="size-4"/></button>:<button disabled={busy} onClick={()=>void finish()} className="inline-flex h-10 items-center gap-2 rounded-[13px] bg-[#163c2d] px-4 text-sm font-semibold text-white disabled:opacity-50"><Check className="size-4"/>{busy?"Saving…":"Start discovering"}</button>}</div></div><div className="mt-4 flex justify-center gap-6 text-[11px] text-[#7c857e]"><span className="inline-flex items-center gap-1"><GitBranch className="size-3"/>GitHub can be connected later</span><span className="inline-flex items-center gap-1"><Sparkles className="size-3"/>Progressive profile</span><span className="hidden items-center gap-1 sm:inline-flex"><Cpu className="size-3"/>Software + hardware</span></div></div>}
function ChoiceScreen({title,description,options,selected,onToggle}:{title:string;description:string;options:string[];selected:string[];onToggle:(x:string)=>void}){return <div><h2 className="text-3xl font-semibold tracking-[-.05em]">{title}</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[#6e786f]">{description}</p><div className="mt-7 grid grid-cols-1 gap-2 sm:grid-cols-2">{options.map(x=><Pick key={x} active={selected.includes(x)} onClick={()=>onToggle(x)}>{x}</Pick>)}</div></div>}
function Pick({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <motion.button whileTap={{scale:.98}} onClick={onClick} className={`flex min-h-12 items-center justify-between rounded-[15px] border px-4 text-left text-sm font-medium transition ${active?"border-[#9cc7aa] bg-[#e8f4ec] text-[#24573e]":"border-black/8 bg-white hover:bg-[#f7f8f5]"}`}>{children}{active&&<Check className="size-4"/>}</motion.button>}
