"use client";
import { cleanDescription, type Opportunity } from "@openforge/domain";
import { motion } from "motion/react";
import { ArrowUpRight, Bookmark, Bot, CalendarDays, CheckCircle2, Clock3, Flame, GitPullRequest, MapPin, Radio, Sparkles, Star } from "lucide-react";
import { useRef, useState } from "react";
import { Badge, GhostButton } from "./ui";
import { MotionDialog, type OriginRect } from "./motion-dialog";
import { springs } from "@/lib/motion";
import { timeAgo } from "@/lib/utils";

type OpportunityPlan = {
  title: string;
  summary: string;
  sections: Array<{ title: string; items: string[] }>;
  nextStep: string;
};

export function OpportunityCard({ item }: { item: Opportunity }) {
  const [saved,setSaved]=useState(false); const [busy,setBusy]=useState(false); const [dialog,setDialog]=useState<null|"explain"|"plan">(null); const [content,setContent]=useState<string>(""); const [plan,setPlan]=useState<OpportunityPlan|null>(null); const [origin,setOrigin]=useState<OriginRect>(null); const card=useRef<HTMLDivElement>(null);
  const open=(kind:"explain"|"plan")=>{const r=card.current?.getBoundingClientRect();setOrigin(r?{left:r.left,top:r.top,width:r.width,height:r.height}:null);setDialog(kind);setContent("");setPlan(null);void load(kind)};
  const load=async(kind:"explain"|"plan")=>{try{const res=await fetch(`/api/forge/${kind}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({opportunity:item})});const data=await res.json();if(kind==="explain")setContent(data.text??"Unable to explain this item right now.");else setPlan(data.plan??null)}catch{setContent("KOBI Agent could not load this analysis. Open the real source and review the original details directly.")}};
  const save=async()=>{const next=!saved;setSaved(next);setBusy(true);try{const res=await fetch("/api/saved",{method:next?"POST":"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({entityType:item.entityType,entityId:item.id,canonicalUrl:item.canonicalUrl,title:item.title,metadata:{source:item.source}})});if(!res.ok&&res.status!==401)throw new Error();if(res.status===401){localStorage.setItem(`KOBI-saved:${item.canonicalUrl}`,String(next))}}catch{setSaved(!next)}finally{setBusy(false)}};
  const href=item.contributionUrl??item.registrationUrl??item.repositoryUrl??item.canonicalUrl;
  const isEvent=item.entityType==="EVENT";
  const summary=cleanDescription(item.shortSummary??item.description,item.title);
  const weather=item.activityScore>=82?"Hot":item.activityScore>=60?"Active":"Slow-moving";
  const eventDate=item.eventDate?new Date(item.eventDate).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}):"Date TBA";
  return <><motion.article ref={card} layout className="surface group relative overflow-hidden rounded-[22px] p-5" whileHover={{y:-2}} transition={springs.snappy}>
    <div className="flex items-start gap-3.5"><div className="grid size-10 shrink-0 place-items-center rounded-[13px] border border-black/7 bg-[#f2f5ef] text-[#244b38]">{isEvent?<CalendarDays className="size-[18px]"/>:item.entityType==="CONTRIBUTION"?<GitPullRequest className="size-[18px]"/>:<Sparkles className="size-[18px]"/>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2 text-[11px] font-semibold uppercase tracking-[.08em] text-[#728075]"><span>{item.source}</span><span className="size-1 rounded-full bg-black/20"/>{item.organization&&<><span className="truncate normal-case tracking-normal">{item.organization}</span></>}</div><h3 className="mt-1.5 text-balance text-[17px] font-semibold leading-6 tracking-[-.03em]">{item.title}</h3><p className="mt-1.5 line-clamp-2 text-[13px] leading-5 text-[#687168]">{summary??(isEvent?"Open the official event page to confirm schedule and registration details.":"Open this source to see the contribution details.")}</p></div><button disabled={busy} onClick={save} aria-label={saved?"Remove from saved":"Save opportunity"} className="focus-ring grid size-9 shrink-0 place-items-center rounded-xl border border-black/7 bg-white transition hover:bg-[#f3f5f1]"><Bookmark className={`size-4 ${saved?"fill-[#163c2d] text-[#163c2d]":""}`}/></button></div>
    <div className="mt-4 flex flex-wrap gap-1.5">{item.goodFirstIssue&&<Badge className="border-[#acd7b9] bg-[#e7f5ec] text-[#215b40]">Good first issue</Badge>}{item.beginnerFriendly&&!item.goodFirstIssue&&<Badge className="border-[#d5ddb0] bg-[#f4f7df] text-[#5b622b]">First-timer friendly</Badge>}{item.hardware&&<Badge>Hardware</Badge>}{[...item.languages,...item.technologies,...item.contributionTypes].filter(Boolean).slice(0,4).map(tag=><Badge key={tag} className="normal-case tracking-normal">{tag}</Badge>)}</div>
    <div className="mt-5 grid grid-cols-3 divide-x divide-black/7 border-y border-black/7 py-3">{isEvent?<><Metric label="Date" value={eventDate} icon={<CalendarDays className="size-3.5"/>}/><Metric label="Mode" value={item.mode==="REMOTE"?"Online":item.mode==="HYBRID"?"Hybrid":item.mode==="PHYSICAL"?"In person":"TBA"} icon={<Radio className="size-3.5"/>}/><Metric label="Place" value={item.location??"Location TBA"} icon={<MapPin className="size-3.5"/>}/></>:<><Metric label="Match" value={`${item.matchScore}%`} icon={<CheckCircle2 className="size-3.5"/>}/><Metric label="Project" value={weather} icon={weather==="Hot"?<Flame className="size-3.5"/>:<Star className="size-3.5"/>}/><Metric label="Activity" value={timeAgo(item.lastActivity)} icon={<Clock3 className="size-3.5"/>}/></>}</div>
    <div className="mt-4 flex flex-wrap items-center gap-2"><a href={href} target="_blank" rel="noreferrer" className="focus-ring inline-flex h-10 flex-1 items-center justify-center gap-2 rounded-[13px] bg-[#163c2d] px-4 text-sm font-semibold text-white transition hover:bg-[#1d503b] sm:flex-none">{isEvent?"Open event":"View contribution"}<ArrowUpRight className="size-4"/></a><GhostButton onClick={()=>open("explain")} className="flex-1 sm:flex-none"><Bot className="size-4"/>Explain</GhostButton><GhostButton onClick={()=>open("plan")} className="hidden sm:inline-flex">{isEvent?"Checklist":"Plan"}</GhostButton></div>
  </motion.article>
  <MotionDialog open={dialog!==null} onClose={()=>setDialog(null)} title={dialog==="plan"?(plan?.title??"KOBI Plan Mode"):"KOBI Agent explanation"} originRect={origin} size="lg">{dialog==="explain"?<div>{content?<div className="whitespace-pre-wrap text-[15px] leading-7 text-[#364039]">{content}</div>:<ExplainSkeleton/>}<div className="mt-6 rounded-[18px] border border-[#b8dbc4] bg-[#eef8f1] p-4 text-sm leading-6 text-[#315641]"><strong>Grounding rule:</strong> KOBI Agent never treats inferred file names, event details, or implementation details as facts. Confirm everything at the real source.</div></div>:<div>{plan?<PlanView plan={plan}/>:<ExplainSkeleton/>}<a href={href} target="_blank" rel="noreferrer" className="mt-6 inline-flex h-11 items-center gap-2 rounded-[14px] bg-[#163c2d] px-5 text-sm font-semibold text-white">Open real source <ArrowUpRight className="size-4"/></a></div>}</MotionDialog></>;
}
function Metric({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <div className="px-3 first:pl-0"><div className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-[.08em] text-[#879088]">{icon}{label}</div><div className="mt-1 truncate text-[13px] font-semibold text-[#29332c]">{value}</div></div>}
function PlanView({plan}:{plan:OpportunityPlan}){return <div className="space-y-5"><p className="text-[15px] leading-7 text-[#354039]">{plan.summary}</p>{plan.sections.map((section,sectionIndex)=><section key={section.title} className="rounded-[18px] border border-black/7 bg-white p-4"><h4 className="text-sm font-semibold tracking-[-.02em] text-[#213228]">{section.title}</h4><ol className="mt-3 space-y-2.5">{section.items.map((step,i)=><motion.li initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:(sectionIndex+i)*.03}} key={`${section.title}-${step}`} className="flex gap-3 text-sm leading-6 text-[#3d473f]"><span className="mt-0.5 grid size-6 shrink-0 place-items-center rounded-full bg-[#e8f4ec] text-[11px] font-bold text-[#24583f]">{i+1}</span><span>{step}</span></motion.li>)}</ol></section>)}<div className="rounded-[18px] border border-[#b8dbc4] bg-[#eef8f1] p-4"><div className="text-xs font-bold uppercase tracking-[.12em] text-[#326248]">Best next step</div><p className="mt-2 text-sm leading-6 text-[#315641]">{plan.nextStep}</p></div></div>}
function ExplainSkeleton(){return <div className="space-y-3"><div className="skeleton h-5 w-2/3 rounded-lg"/><div className="skeleton h-4 w-full rounded-lg"/><div className="skeleton h-4 w-[92%] rounded-lg"/><div className="skeleton h-4 w-[78%] rounded-lg"/><div className="mt-6 skeleton h-28 w-full rounded-[18px]"/></div>}
